### ISSUE TITLE
mac下编译报错

### ISSUE THREAD

**Issue by mewtwoNeo** [zhangtao07/fis-vuejs-seed#7]
[ERROR] load plugin [fis-parser-node-sass] config error : Error: The `libsass` binding was not found in /Users/mewtwo/work/workspace/discovery/fis-vuejs-seed/node_modules/fis-parser-node-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

This usually happens because your node version has changed.

是这个插件有问题吗？还是对node版本有依赖？

**Comment by zhangtao07** [comment]
sass插件请用 cnpm(3.x)安装，否则很容易被墙，sass 并不是必须的，可以用 less，插件安装不会碰到这种问题
